// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankingSystem.Models;

public partial class Account
{
    public Guid AccountId { get; set; }

    public string OwnerId { get; set; }

    public string OwnerName { get; set; }

    public decimal Balance { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}