// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankingSystem.Models;

public partial class Transaction
{
    public Guid TransactionId { get; set; }

    public Guid AccountId { get; set; }

    public int Type { get; set; }

    public decimal Amount { get; set; }

    public DateTime OccurredOn { get; set; }

    public Guid? DestinationAccountId { get; set; }

    public virtual Account Account { get; set; }
}